version: '3.8'

services:
  album-fights:
    image: earlofburl/album-fights:latest  # Change 'earlofburl' to your docker username later
    container_name: album-fights
    ports:
      - "8282:80"
    volumes:
      - ./data:/var/www/html/data
      - ./cache:/var/www/html/cache
    restart: unless-stopped